export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const DELIVERY_REPOSITORY = 'DELIVERY_REPOSITORY';
